# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Project Configuration
project.name=ANIP
project.url=https://github.com/BetterAndroid/android-notification-icon-project
project.groupName=com.highcapable.anip
project.android.compileSdk=37
project.android.minSdk=21
project.android.targetSdk=37
project.samples.demo.packageName=${project.groupName}.demo
project.samples.demo.versionName=universal
project.samples.demo.versionCode=1
project.anip-sdk.namespace=${project.groupName}.sdk
project.anip-sdk.version="1.0.0"
# Maven Publish Configuration
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
# Maven POM Configuration
POM_NAME=ANIP
POM_DESCRIPTION=Provides standardized monochrome icon resources for apps and vendor systems that do not conform to the Android standard notification design.
POM_URL=https://github.com/BetterAndroid/android-notification-icon-project
POM_LICENSE_NAME=Apache License 2.0
POM_LICENSE_URL=https://github.com/BetterAndroid/android-notification-icon-project/blob/main/LICENSE
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/BetterAndroid/android-notification-icon-project
POM_SCM_CONNECTION=scm:git:git://github.com/BetterAndroid/android-notification-icon-project.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/BetterAndroid/android-notification-icon-project.git
POM_DEVELOPER_ID=0
POM_DEVELOPER_NAME=fankes
POM_DEVELOPER_EMAIL=qzmmcn@163.com
POM_DEVELOPER_URL=https://github.com/fankes